### ISSUE TITLE
Hold Github Onboarding

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#362] opened 2021-02-02 20:39 UTC
- [x] Add folks to the github (@lourdesvera )
- [x]  Schedule
- [x] Gather materials
- [x] hold onboarding

**Comment by Frijol** [comment] 2021-02-02 20:42
Now scheduled for Friday

**Comment by Frijol** [comment] 2021-02-02 22:31
duplicate of https://github.com/edgi-govdata-archiving/EEW_Planning/issues/356

**Comment by Frijol** [comment] 2021-02-02 22:32
Also of https://github.com/edgi-govdata-archiving/EEW_Planning/issues/343. Have closed both those other issues to let this be the canonical issue.

**Closed** 2021-02-05 19:39 UTC
Labels: internal care
