### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by calderEDJ** [edgi-govdata-archiving/EEW_Planning#58] opened 2020-04-23 19:46 UTC
come up with naming conventions for notebooks and apply them

┆Issue is synchronized with this [Trello card](https://trello.com/c/FOcQwQOC)

**Comment by Frijol** [comment] 2020-05-12 17:38
Is this separate from https://github.com/edgi-govdata-archiving/EEW_Planning/issues/55?

**Comment by Frijol** [comment] 2020-05-28 23:27
closing as it seems to be a duplicate of https://github.com/edgi-govdata-archiving/EEW_Planning/issues/55

**Closed by Frijol** 2020-05-28 23:27 UTC
