### ISSUE TITLE
Notebook Validation Process

### ISSUE THREAD

**Issue by mraisle** [edgi-govdata-archiving/EEW_Planning#203] opened 2020-06-23 19:19 UTC
┆Issue is synchronized with this [Trello card](https://trello.com/c/X1Eaiatv)

**Comment by mraisle** [comment] 2020-06-23 19:20
@Frijol and @ericnost would you like to be assigned to this?

**Comment by Frijol** [comment] 2020-06-25 01:25
this is a duplicate of https://github.com/edgi-govdata-archiving/EEW_Planning/issues/197, closing

**Closed by Frijol** 2020-06-25 01:25 UTC
Labels: database, notebooks Jupyter
