### ISSUE TITLE
ESIP Demo Video

### ISSUE THREAD

**Issue by mraisle** [edgi-govdata-archiving/EEW_Planning#199] opened 2020-06-23 19:08 UTC
┆Issue is synchronized with this [Trello card](https://trello.com/c/3p2wzEdh)

**Comment by mraisle** [comment] 2020-06-23 19:08
@gabrielletrudo  do you want to assign yourself to this?

**Comment by Frijol** [comment] 2020-06-29 21:54
this issue is a duplicate of https://github.com/edgi-govdata-archiving/EEW_Planning/issues/174, please pick which one is most useful & close the other

**Comment by Frijol** [comment] 2020-06-30 18:42
Video: https://files.slack.com/files-pri/T32U2HQG1-F015QDLECS2/download/eew_promo_video.mp4

**Comment by Frijol** [comment] 2020-07-01 22:22
@calderEDJ is that file ^ still the right link?

Feedback:
* Timestamp 1:49 I think the accidental text "ate" is in the middle of the page?
* Recommend highlighting behind text, it's hard to read on top of the videos
* Would be useful to compare with existing EPA site? Talk about user feedback maybe?
* Show/go into results for an area a bit? A lot of time is spent on the notebook itself but it might be more powerful to show that you can run a notebook --> show the kind of compelling graphics that can emerge from there rather than keep scrolling the notebook

**Comment by lourdesvera** [comment] 2020-07-07 16:21
Did it! Thank you @calderEDJ and @crgreenleaf

**Closed by lourdesvera** 2020-07-07 16:21 UTC
Labels: communications, documentation, needs more assignees
