### ISSUE TITLE
Sign up for River Rally 2021 https://www.rivernetwork.org/connect-learn/river-rally/program/

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#364] opened 2021-02-02 20:39 UTC
- [x] Discuss joining river network or paying $279 registration fee
- [x] Who will go?
- [x] Register
 https://www.rivernetwork.org/connect-learn/river-rally/program/

**Comment by saraannwylie** [comment] 2021-02-02 21:04
Eliza from Wylie lab is already registered and we are presenting landlosslookout, we could also mention this project in that presentation. Let's ask in slack if anyone is eager to go? I think we have fund remaining from unpaid hours last semester we could use to cover the fee?

**Comment by Frijol** [comment] 2021-02-02 21:59
duplicate of https://github.com/edgi-govdata-archiving/EEW_Planning/issues/346

**Comment by Frijol** [comment] 2021-03-02 17:55
Are we signed up? Should this issue be closed?

**Closed** 2021-03-10 15:28 UTC
Labels: Outreach, external care, research care
